/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Android: typeof import('./src/components/ui/Android.vue')['default']
    Card: typeof import('./src/components/ui/Card.vue')['default']
    ElegantShape: typeof import('./src/components/ui/ElegantShape.vue')['default']
    FeaturesSection: typeof import('./src/components/ui/FeaturesSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HeroGeometric: typeof import('./src/components/ui/HeroGeometric.vue')['default']
    Laptop: typeof import('./src/components/ui/Laptop.vue')['default']
    LayoutGrid: typeof import('./src/components/ui/LayoutGrid.vue')['default']
    Motion: typeof import('motion-v')['Motion']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pricing: typeof import('./src/components/ui/Pricing.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotlightNew: typeof import('./src/components/ui/SpotlightNew.vue')['default']
    SpotlightNewDemo: typeof import('./src/components/ui/SpotlightNewDemo.vue')['default']
  }
}
